### ISSUE TITLE
Installing dependencies issue with database version

### ISSUE THREAD

**Issue by jhirscher** [ddev/ddev-platformsh#141]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV
- [x] I am using the latest stable version of this add-on

### Expected Behavior

Executing `ddev add-on get ddev/ddev-platformsh` in my project to make sure I am using the latest version and because my .platform/services.yaml file changed should return a successful message and let me start DDEV.

### Actual Behavior

> $ ddev add-on get ddev/ddev-platformsh
> Installing ddev/ddev-platformsh:v0.8.2 
> v0.8.2_2790268493.tar.gz 1.12 MiB / ? [-----------------------------------=-------------------------------------------------------------------] 11746.44% 0s 
> 
> Executing pre-install actions: 
> 👍 check project type 
> Using existing PLATFORMSH_CLI_TOKEN.
>  
> 👍 Setting PLATFORMSH_CLI_TOKEN 
> Using existing PLATFORM_PROJECT from project config.yaml.
>  
> 👍 Set PLATFORM_PROJECT 
> 👍 Setting PLATFORM_APPLICATION_NAME 
> Using existing PLATFORM_ENVIRONMENT from project config.yaml.
>  
> 
> Installing project-level components: 
> 👍 web-build/Dockerfile.platformsh 
> 👍 homeadditions/.bashrc.d/platformsh-environment.sh 
> 👍 platformsh/.gitignore 
> 👍 platformsh/generate_db_relationship.sh 
> 👍 platformsh/generate_elasticsearch_relationship.sh 
> 👍 platformsh/generate_memcached_relationship.sh 
> 👍 platformsh/generate_opensearch_relationship.sh 
> 👍 platformsh/generate_redis_relationship.sh 
> 👍 platformsh/generate_redis-persistent_relationship.sh 
> 👍 platformsh/generate_route.sh 
> 
> Installing global components: 
> 👍 commands/web/platform 
> 
> Executing post-install actions: 
> 👍 Support composer and python3 dependencies 
> 👍  Install .environment file into web-entrypoint.d if needed 
> 👎 Installing dependencies and generating needed environment variables 
> 
> 
> There is an existing database in this project that doesn't match the upstream database type.
>  Please use 'ddev delete' to delete the existing database and retry, or try 'ddev debug migrate-database mariadb' to migrate the database.
>  
> Could not process post-install action (3) 'Installing dependencies and generating needed environment variables'

When I run `ddev debug check-db-match`, I get:
database in volume matches configured database: mariadb:10.6

When I run ` ddev debug get-volume-db-version`, I get:
mariadb:10.6

I have tried ddev delete and starting over several times, but I get this error everytime.

I'm not sure how to get past this. The database info remained unchanged in the services.yaml file.

### Anything else?

```
name: drupal
type: drupal11
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames:
    - default
    - sea
additional_fqdns: []
database:
    type: mariadb
    version: "10.6"
use_dns_when_possible: true
composer_version: "2"

```

This is the .ddev/config.platformsh.yaml

```
disable_settings_management: true
php_version: 8.3
composer_version: "2"
database:
  type: mariadb
  version: "10.6"
docroot: web
webimage_extra_packages:
- figlet
```

**Comment by rfay** [comment]
Please provide the file output by `ddev debug test` and the `.ddev/config.platformsh.yaml`, and the output of `ddev delete -Oy`. Thanks.

**Comment by rfay** [comment]
If you haven't sorted this out @jhirscher I'll be happy to help you on a call, https://cal.com/randyfay/30min

**Comment by jhirscher** [comment]
@stasadev Yes, our .platform/services.yaml contains:

```
db:
    type: 'mariadb:10.6'
    disk: 10000
    configuration:
        schemas:
            - drupal
            - drupal_secure
        endpoints:
            main:
                default_schema: drupal
                privileges:
                    drupal: admin
            sea:
                default_schema: drupal_secure
                privileges:
                    drupal_secure: admin
```


My colleague got an environment going again, and the problem seems to be the fact that we have a Drupal multi-site with two databases, as you can see above. When establishing our local dev environments, we had made some changes that were not documented. 

The long-story is that after executing `ddev add-on get ddev/ddev-platformsh`, we end up needing to edit the values in the PRIMARY_RELATIONSHIPS in config.platformsh.yaml to get it to load the databases as we have them defined in the .platform/services.yaml, but that means subsequent `ddev add-on get ddev/ddev-platformsh` commands fail with the above message. However, if doing a `ddev delete` as instructed by the failure message and starting over, that re-establishes the config.platformsh.yaml file which has the PRIMARY_RELATIONSHIPS that are incorrect. The the local environments do not load properly.  

Do we have something misconfigured to make the PRIMARY_RELATIONSHIPS that are output invalid, or is this just the nature of us running multi-site which is not supported with the add-on?
